language: c
dist: bionic
compiler: clang 
arch:
- amd64
- arm64

script:
- clang --version 
- gcc --version
- whereis gcc
#- cat /usr/lib/gcc/aarch64-linux-gnu/7.5.0/include/stddef.h
- clang try.c
- ./a.out
