language: c
dist: bionic
compiler: clang 
arch:
- amd64
- arm64

script:
- clang --version 
- gcc --version
- whereis gcc
#- cat /usr/lib/gcc/aarch64-linux-gnu/7.5.0/include/stddef.h
- gcc try.c -o try_gcc
- ./try_gcc
- clang try.c -o try_clang
- ./try_clang
